services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: personal
      POSTGRES_DB: app_db
    volumes: [pg:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/app_db
    ports:
      - "8000:8000"
    entrypoint:
      "uvicorn backend.app:app --host 0.0.0.0 --port 8000 --no-access-log --reload"

  frontend:
    build: ./frontend
    depends_on: [backend]
    ports: ["8080:80"]

volumes:
  pg:
