services:

  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}

    volumes: [pg:/var/lib/postgresql/data]
    ports: ["${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"]

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    environment:
      PG_ADMIN_PORT: ${PG_ADMIN_PORT}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PG_ADMIN_PORT}:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_DB_PORT}/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    entrypoint:
      "uvicorn backend.app:app --host 0.0.0.0 --port ${BACKEND_PORT} --no-access-log --reload"

  frontend:
    build: ./frontend
    env_file: .env
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    depends_on: [backend]
    ports: ["${FRONTEND_PORT}:${FRONTEND_PORT}"]

volumes:
  pg:
